products = [
    {
        '_id':1,
        'productname':'TV',
        'category':'electronics',
        'price':1000
    },
    {
        '_id':2,
        'productname':'Laptop',
        'category':'electronics',
        'price':1200
    },
    {
        '_id':3,
        'productname':'Mobile',
        'category':'electronics',
        'price':600
    },    
]