# Generated by Django 5.1 on 2024-09-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_rename_product_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='numReview',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
